/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cn.udian.communicationprotocol.szstandard.thriftservice;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ActionResultType implements org.apache.thrift.TEnum {
  SUCCESS(0),
  TERMINAL_NOT_CONNECTED(1),
  TERMINAL_CONNECTING_WITH_OTHER_ACCESSER(2),
  FAIL_WITH_OTHER_RESONE(3);

  private final int value;

  private ActionResultType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ActionResultType findByValue(int value) { 
    switch (value) {
      case 0:
        return SUCCESS;
      case 1:
        return TERMINAL_NOT_CONNECTED;
      case 2:
        return TERMINAL_CONNECTING_WITH_OTHER_ACCESSER;
      case 3:
        return FAIL_WITH_OTHER_RESONE;
      default:
        return null;
    }
  }
}
