/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cn.udian.communicationprotocol.szstandard.thriftservice;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum CaptureJpegDeviceType implements org.apache.thrift.TEnum {
  CAPTUREJPEGDEVICETYPE_DVR(0),
  CAPTUREJPEGDEVICETYPE_OTHER(255);

  private final int value;

  private CaptureJpegDeviceType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static CaptureJpegDeviceType findByValue(int value) { 
    switch (value) {
      case 0:
        return CAPTUREJPEGDEVICETYPE_DVR;
      case 255:
        return CAPTUREJPEGDEVICETYPE_OTHER;
      default:
        return null;
    }
  }
}
