/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cn.udian.communicationprotocol.szstandard.thriftservice;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum MultimediaQuality implements org.apache.thrift.TEnum {
  MULTIMEDIAQUALITY_BEST(0),
  MULTIMEDIAQUALITY_BETTER(1),
  MULTIMEDIAQUALITY_MEDIUM(2),
  MULTIMEDIAQUALITY_LOWER(3),
  MULTIMEDIAQUALITY_LOWEST(4);

  private final int value;

  private MultimediaQuality(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static MultimediaQuality findByValue(int value) { 
    switch (value) {
      case 0:
        return MULTIMEDIAQUALITY_BEST;
      case 1:
        return MULTIMEDIAQUALITY_BETTER;
      case 2:
        return MULTIMEDIAQUALITY_MEDIUM;
      case 3:
        return MULTIMEDIAQUALITY_LOWER;
      case 4:
        return MULTIMEDIAQUALITY_LOWEST;
      default:
        return null;
    }
  }
}
