/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cn.udian.communicationprotocol.szstandard.thriftservice;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum NotificationStyle implements org.apache.thrift.TEnum {
  VIBRATE(0),
  VOICE(1);

  private final int value;

  private NotificationStyle(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static NotificationStyle findByValue(int value) { 
    switch (value) {
      case 0:
        return VIBRATE;
      case 1:
        return VOICE;
      default:
        return null;
    }
  }
}
