/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cn.udian.communicationprotocol.szstandard.thriftservice;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum OperatingDetailType implements org.apache.thrift.TEnum {
  GO_INTO_OPERATING(0),
  CHARGING_OR_FILLING(1),
  MAINTENANCE(2),
  MIDWAY_OBSACLE(3),
  SERVICE(4),
  BUSINESS(5),
  CHARTERED(6),
  CUSTOMIZED_BUS(7),
  IN_STATION(8),
  OTHER(9),
  STATION_BUSINESS(10),
  GO_INTO_LINE_UP(11),
  GO_INTO_LINE_DOWN(12),
  UNKNOW_DETAIL_TYPE(255);

  private final int value;

  private OperatingDetailType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static OperatingDetailType findByValue(int value) { 
    switch (value) {
      case 0:
        return GO_INTO_OPERATING;
      case 1:
        return CHARGING_OR_FILLING;
      case 2:
        return MAINTENANCE;
      case 3:
        return MIDWAY_OBSACLE;
      case 4:
        return SERVICE;
      case 5:
        return BUSINESS;
      case 6:
        return CHARTERED;
      case 7:
        return CUSTOMIZED_BUS;
      case 8:
        return IN_STATION;
      case 9:
        return OTHER;
      case 10:
        return STATION_BUSINESS;
      case 11:
        return GO_INTO_LINE_UP;
      case 12:
        return GO_INTO_LINE_DOWN;
      case 255:
        return UNKNOW_DETAIL_TYPE;
      default:
        return null;
    }
  }
}
